# Generated by Django 2.1.3 on 2018-12-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181211_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=200, verbose_name='备注')),
            ],
        ),
    ]
