# Generated by Django 2.1.3 on 2018-12-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='question',
            field=models.ManyToManyField(to='news.Question'),
        ),
    ]
